(import hello)
(import srfi-4)
(display "Defining new vector x...\n")
(define x (f64vector 0 1 2))
(display x) (newline)
(display "Incrementing elements of x in-place...\n")
(ScmIncVec x)
(display "Result:\n")
(display x) (newline)
(exit 0)
